spring.application.name=farmfood

# Thymeleaf
spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:true}
spring.thymeleaf.mode=HTML


# Database Supabase
spring.datasource.url=jdbc:postgresql://db.ofdyfdgponosxnpdgrux.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=171204Flavio@
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
